### ISSUE TITLE
onSelect never fires

### ISSUE THREAD

**Issue by kadosh1000** [aksonov/react-native-tabs#10]
Hi this is my view 

`<View style={styles.mainContainer}> 
        <Tabs style={{backgroundColor:'white'}}
              onSelect={function(el){
                self.setState({
                  category: el.props.name, 
                  page:0
                }); 
                self.GetInitialPage();
                return {style:{color:'red'}}
              }}>
            <Text name="finanace&">השקעות</Text>
            <Text name="technology&">טכנולוגי</Text>
            <Text name="marketsection&">שיווק</Text>
            <Text name="entrepsection&">יזמות</Text>
        </Tabs>
        <ListView
          dataSource={this.state.articles}
          renderRow={this.renderArticleSnippet}
          style={styles.listView}
          onEndReachedThreshold={200}
          onEndReached={this.GetNextPage}/>
        </View>` 

The onSelect action never fires, also tried putting a break point in the module's onSelect function but it never gets fired either. what may cause that?

**Comment by devux** [comment]
what is the solution for this?
