### ISSUE TITLE
Selected Can't Change Props

### ISSUE THREAD

**Issue by skytoup** [aksonov/react-native-tabs#12]
line 60:
{!self.props.selected && (self.state.selected == el.props.name) ? React.cloneElement(el, self.state.props) : el}

Should be?

{!self.props.locked && (self.state.selected == el.props.name) ? React.cloneElement(el, self.state.props) : el}

**Comment by chetstone** [comment]
Not sure what you're trying to do here. The `locked` prop is only for enabling the `onLongPress` action and disabling `onPress`. It has nothing to do with rendering. Could you provide more details on the problem you're seeing?

**Comment by aksonov** [comment]
Please check latest version, now component is totally stateless.
