### ISSUE TITLE
Remove Opacity when button is clicked

### ISSUE THREAD

**Issue by KishPatel1996** [aksonov/react-native-tabs#30]
Is there a way to prevent touchableopacity when a tab is clicked?

Another solution may be to set activeOpacity to 1.0, but not sure where to do that as well.  Any help on this would be appreciated!

**Comment by KishPatel1996** [comment]
Any help on this would be greatly appreciated.  thanks

**Comment by Shakarang** [comment]
Hey @KishPatel1996 

What is did is to directly modify the `react-native-tabs` module in my app.

In the `index.js` file line 36 you have the `TouchableOpacity` component.

Just add this property will do the trick but when it will be erased when you will update the module.

```
activeOpacity={1}
```

Check this PR : #32

**Comment by KishPatel1996** [comment]
Hi @Shakarang , thanks for the answer!

**Comment by nguyenvanphuc2203** [comment]
@Shakarang tks! it exactly my issue
