### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by wtfil** [aksonov/react-native-tabs#34]
Hi!
Can you please bump version of the library, in order to have [this](https://github.com/aksonov/react-native-tabs/blob/master/index.js#L40) functionality from npm package.

Thank you

**Comment by Shakarang** [comment]
@aksonov ?

**Comment by aksonov** [comment]
Sorry, didn't write, but i've done it at that day :)

**Comment by wtfil** [comment]
@aksonov thx!
I will close the issue
