### ISSUE TITLE
Not working on android

### ISSUE THREAD

**Issue by kakoni** [aksonov/react-native-tabs#4]
Hi, running example with react 0.13.3/native 0.11.4. It looks like this;
![image](https://cloud.githubusercontent.com/assets/812150/10301943/3a23158e-6c10-11e5-9f1b-9ab1864dc4fe.png)

**Comment by aksonov** [comment]
Hm, i will look, but it seems flex layout works differently on iOS and Android...

**Comment by webwelten** [comment]
No, there's another problem which I've had on iOS as well. From the issue comment:

```
<TouchableOpacity key={el.key+"touch"} style={styles.iconView} onPress={()=>self.onSelect(el)}>
    {React.cloneElement(el, self.state[el.props.name])}
</TouchableOpacity>
```

`el.key` is not defined which means that every Component gets the same key and react throws the following error:

> Warning: flattenChildren(...): Encountered two children with the same key, `.$nulltouch`. Child keys 
> must be unique; when two children share a key, only the first child will be used.

Therefore it should be:
`key={el.props.name+'touch'}`
