### ISSUE TITLE
Display Tab View on Top

### ISSUE THREAD

**Issue by ghost** [aksonov/react-native-tabs#43]
How can I display the top view at the top of the screen, you have mentioned that it supports both top and bottom view, but I am not even able to see any property.
Kindly add properties and please also include the installation top your documentation, how to install it.

Thanks

**Comment by DonovanCharpin** [comment]
Hi @RishiAnkush,

Did you close the issue because you found the answer?
Could be nice to share the answer with us.

**Comment by lamdn** [comment]
```
      <View style={styles.containerTabs}>
          <Tabs
            selected={page}
            style={styles.itemTabbar}
            selectedStyle={{backgroundColor:'red'}} onSelect={el=>this.setState({page:el.props.name})}>
              <Text name="first">first</Text>
              <Text name="second">second</Text>
              <Text name="third">third</Text>
          </Tabs>
      </View>
```

const styles = StyleSheet.create({
    itemTabbar: {
          **top: 0**
    }
});
