### ISSUE TITLE
[Android] Page re-renders every-time I change tab.

### ISSUE THREAD

**Issue by han4wluc** [aksonov/react-native-tabs#6]
I have a listview in my page content, which loads some data from online.
But each time I switch to the tab, it re-renders making a new http request.
Is there a way to not re-render the page when I switch tab??

**Comment by aksonov** [comment]
This component doesn't manage content, it is more like 'multi' button - you have to manage content by yourself. OR you could use react-native-router-flux with Container element to manage connect, so it will not re-render data each time, check react-native-router-flux demo project.
