### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by dangnelson** [aksonov/react-native-tabs#8]
I copy and pasted your example, but the tabs don't all appear, only the "First" tab appears bottom and center.

**Comment by zebulgar** [comment]
you're right! taking a look at this now

**Comment by zebulgar** [comment]
@aksonov looks like the example hasn't had the package.json updated to the latest version. It also seems like there is an issue with not having unique keys, however even when I fix that there is a rendering issue on the tabs. I can dig into this more next time I set aside more time for this project

**Comment by ktastrophy** [comment]
I think I found the issue here. I'll send a PR if it works out.

**Comment by aksonov** [comment]
I ve solved issue with keys but now it doesn't select tab with red color 

Pavel.

**Comment by ktastrophy** [comment]
Changing

```
{!self.props.selected && (self.state.selected == el.props.name) ? React.cloneElement(el, self.state.props) : el}
```

To 

```
{self.props.selected && (self.state.selected == el.props.name) ? React.cloneElement(el, self.state.props) : el}
```

Fixed it for me. I'd be lying if I said I fully understood what that `!self.props.selected &&` was for

**Comment by zebulgar** [comment]
That was for an issue where the react native tab was overriding the selected prop with its internal state prop

**Comment by zebulgar** [comment]
Fixes an issue with the integration with react native flux router but @askonov there might be a better way than how I've done it

**Comment by belvikram** [comment]
How to add Contents into each tab ?

**Comment by aksonov** [comment]
Should be fixed, please check latest version
